CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  contrasena TEXT,
  rol TEXT DEFAULT 'lector',
  nivel INT DEFAULT 1
);

CREATE TABLE articulos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  tipo TEXT, 
  vistas INT DEFAULT 0,
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  autor_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE multimedia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT,
  tipo TEXT,
  descripcion TEXT
);

CREATE TABLE eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo_id BIGINT NOT NULL REFERENCES articulos(id) ON DELETE CASCADE,
  nombre TEXT,
  fecha_ini TIMESTAMP WITH TIME ZONE,
  fecha_fin TIMESTAMP WITH TIME ZONE,
  ubicacion TEXT,
  sinopsis TEXT,
  UNIQUE(articulo_id)
);

CREATE TABLE grupos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo_id BIGINT NOT NULL REFERENCES articulos(id) ON DELETE CASCADE,
  nombre TEXT,
  lider_nombre TEXT,
  descripcion TEXT,
  UNIQUE(articulo_id)
);

CREATE TABLE personas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo_id BIGINT NOT NULL REFERENCES articulos(id) ON DELETE CASCADE,
  nombre TEXT,
  apodos TEXT,
  cumpleanos TIMESTAMP WITH TIME ZONE,
  telefono TEXT,
  direccion TEXT,
  estado TEXT,
  lore_general TEXT,
  evento_destacado_id BIGINT REFERENCES eventos(id) ON DELETE SET NULL,
  UNIQUE(articulo_id)
);

CREATE TABLE secciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  articulo_id BIGINT NOT NULL REFERENCES articulos(id) ON DELETE CASCADE,
  titulo TEXT,
  cuerpo TEXT,
  nivel INT,
  orden INT,
  seccion_padre_id BIGINT REFERENCES secciones(id) ON DELETE SET NULL,
  tipo TEXT DEFAULT 'texto' CHECK (tipo IN ('texto', 'imagen', 'video')),
  multimedia_id INT REFERENCES multimedia(id) ON DELETE CASCADE
);

CREATE TABLE multimedia_articulos (
  articulo_id BIGINT NOT NULL REFERENCES articulos(id) ON DELETE CASCADE,
  multimedia_id BIGINT NOT NULL REFERENCES multimedia(id) ON DELETE CASCADE,
  PRIMARY KEY (articulo_id, multimedia_id)
);

CREATE TABLE personas_grupos (
  persona_id BIGINT NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  grupo_id BIGINT NOT NULL REFERENCES grupos(id) ON DELETE CASCADE,
  PRIMARY KEY (persona_id, grupo_id)
);

CREATE TABLE personas_eventos (
  persona_id BIGINT NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  evento_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
  rol_en_evento TEXT,
  PRIMARY KEY (persona_id, evento_id)
);

CREATE TABLE grupos_eventos (
  grupo_id BIGINT NOT NULL REFERENCES grupos(id) ON DELETE CASCADE,
  evento_id BIGINT NOT NULL REFERENCES eventos(id) ON DELETE CASCADE,
  PRIMARY KEY (grupo_id, evento_id)
);

CREATE TABLE personas_relaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_origen_id BIGINT NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  persona_destino_id BIGINT NOT NULL REFERENCES personas(id) ON DELETE CASCADE,
  UNIQUE(persona_origen_id, persona_destino_id)
);